<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [1]:
import numpy as np
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

x = np_array
print(x[::-1])
print(x[1:5])

['j10' 'i9' 'h8' 'g7' 'f6' 'e5' 'd4' 'c3' 'b2' 'a1']
['b2' 'c3' 'd4' 'e5']


## 1.2 Arrays only | Subsetting by masking

In [14]:
np_array_1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
x = np_array_1> 3
print(x)

[False False False  True  True  True  True  True  True  True]


In [3]:
print(np_array[x])

[ 4  5  6  7  8  9 10]


In [22]:
print(np_array[np_array_1> 3])
print(np_array[~(np_array_1>3)])
print(np_array[(np_array_1> 3) & (np_array_1< 8)])
print(np_array[(np_array_1 < 3) | (np_array_1 > 8)])

[ 4  5  6  7  8  9 10]
[1 2 3]
[4 5 6 7]
[ 1  2  9 10]


## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [23]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [24]:
print(py_list_2d[3])
print(np_array_2d[3])

[4, 'D']
['4' 'D']


In [27]:
print(py_list_2d[3][0])
print(np_array_2d[3,0])
print(py_list_2d[3][1])
print(np_array_2d[3,1])

4
4
D
D


In [28]:
print(py_list_2d[:3])
print(np_array_2d[:3])

[[1, 'A'], [2, 'B'], [3, 'C']]
[['1' 'A']
 ['2' 'B']
 ['3' 'C']]


In [32]:
print(py_list_2d[:3][0])
print(np_array_2d[:3, 0])

[1, 'A']
['1' '2' '3']


In [36]:
print(py_list_2d[3:7][0])
print(np_array_2d[2:6, 0])
print(np_array_2d[:, 0])

[4, 'D']
['3' '4' '5' '6']
['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


## 1.4 Growing lists

In [37]:
x=[1,2]*4
print(x)

[1, 2, 1, 2, 1, 2, 1, 2]


In [40]:
x=[1]
x=x+[2]
print(x)

[1, 2]


In [41]:
x=[1]
x+=[2]
print(x)

[1, 2]


In [46]:
x=[1]
x.append(2)
print(x)

[1, 2]


In [47]:
x = [1, 2, 3]
x+= [4, 5, 6]
print(x)

[1, 2, 3, 4, 5, 6]

In [49]:
x=[1, 2, 3]
x.extend([4, 5, 6])
print(x)

[1, 2, 3, 4, 5, 6]


In [50]:
x=[1, 2, 3]
x.append([4, 5, 6])
print(x)

[1, 2, 3, [4, 5, 6]]


# Some loose ends

## 1.5 Tuples

In [52]:
a=(1,2)
print(a[1])

2


In [53]:
a[0]+=[10]

TypeError: unsupported operand type(s) for +=: 'int' and 'list'

## 1.6 Be VERY careful when copying

In [55]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()
print(y)
print(z)

[1, 2, 3]
[1, 2, 3]


# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes